/* DEPT_INFO view */
create view SWCOMPANY.DEPT_INFO (Dept_id, Dept_type, Dept_state, Dept_city, Dept_street, Dept_mgr)
as select  SWCOMPANY.DEPARTMENT.Dept_id, SWCOMPANY.DEPARTMENT.Dept_type, SWCOMPANY.LOC_ADDRESS.State, 
		  SWCOMPANY.LOC_ADDRESS.City, SWCOMPANY.LOC_ADDRESS.Street, SWCOMPANY.EMPLOYEE.Fname
from SWCOMPANY.DEPARTMENT, SWCOMPANY.LOCATED_AT, SWCOMPANY.LOC_ADDRESS, SWCOMPANY.EMPLOYEE
where SWCOMPANY.DEPARTMENT.Dept_id = SWCOMPANY.LOCATED_AT.Department_id and SWCOMPANY.LOC_ADDRESS.Location_id = SWCOMPANY.LOCATED_AT.Location_id 
	  and SWCOMPANY.DEPARTMENT.Dept_mgr_id = SWCOMPANY.EMPLOYEE.Emp_id;
      
/* PROD_INFO view */
create view SWCOMPANY.PROD_INFO (Prod_name, Rsheet_id, Bom_id, Prod_price)
as select SWCOMPANY.PRODUCT.Name, SWCOMPANY.ROUTING_SHEET.Sheet_id, SWCOMPANY.BOM.Bom_id, SWCOMPANY.PRODUCT.price
from SWCOMPANY.PRODUCT, SWCOMPANY.ROUTING_SHEET, SWCOMPANY.BOM
where SWCOMPANY.PRODUCT.Product_id = SWCOMPANY.ROUTING_SHEET.Product_id and SWCOMPANY.PRODUCT.Product_id = SWCOMPANY.BOM.Product_id;

/* EMP_INFO */
create view SWCOMPANY.EMP_INFO (Emp_id, Emp_fname, Emp_lname, Gender, Job_type, Dept_type, Phone, Email)
as select SWCOMPANY.EMPLOYEE.Emp_id, SWCOMPANY.EMPLOYEE.Fname, SWCOMPANY.EMPLOYEE.Lname, SWCOMPANY.EMPLOYEE.Gender, SWCOMPANY.EMPLOYEE.Job_type, 
		  SWCOMPANY.DEPARTMENT.Dept_type, SWCOMPANY.EMPLOYEE.Phone, SWCOMPANY.EMPLOYEE.Email
from SWCOMPANY.EMPLOYEE, SWCOMPANY.DEPARTMENT
where SWCOMPANY.EMPLOYEE.Dept_id = SWCOMPANY.DEPARTMENT.Dept_id
order by SWCOMPANY.EMPLOYEE.Emp_id asc;

/* CUST_INFO */
create view SWCOMPANY.CUST_INFO (Cust_fname, Cust_lname, Phone, Email, Cust_state, Cust_city, Cust_street)
as select SWCOMPANY.CUSTOMER.Fname, SWCOMPANY.CUSTOMER.Lname, SWCOMPANY.CUSTOMER.Phone, SWCOMPANY.CUSTOMER.Email, 
		  SWCOMPANY.CUST_SHIP_ADDRESS.State, SWCOMPANY.CUST_SHIP_ADDRESS.City, SWCOMPANY.CUST_SHIP_ADDRESS.Street
from SWCOMPANY.CUSTOMER, SWCOMPANY.CUST_SHIP_ADDRESS
where SWCOMPANY.CUSTOMER.Customer_id = SWCOMPANY.CUST_SHIP_ADDRESS.Customer_id
order by SWCOMPANY.CUSTOMER.Customer_id asc;

/* ORDER_INFO */
create view SWCOMPANY.ORDER_INFO (Order_id, Customer_fname, Customer_lname, Product_name, Quantity, Prod_price, Delivery_type)
as select SWCOMPANY.ORDER.Order_id, SWCOMPANY.CUSTOMER.Fname, SWCOMPANY.CUSTOMER.Lname, SWCOMPANY.PRODUCT.Name, SWCOMPANY.PRODUCT_W_ORDER.Quantity, 
		  SWCOMPANY.PRODUCT.price, SWCOMPANY.PRODUCT_W_ORDER.Delivery_type
from SWCOMPANY.ORDER, SWCOMPANY.CUSTOMER, SWCOMPANY.PRODUCT, SWCOMPANY.PRODUCT_W_ORDER
where SWCOMPANY.ORDER.Customer_id = SWCOMPANY.CUSTOMER.Customer_id and SWCOMPANY.ORDER.Order_id = SWCOMPANY.PRODUCT_W_ORDER.Order_id 
			and SWCOMPANY.PRODUCT_W_ORDER.Product_id = SWCOMPANY.PRODUCT.Product_id;

/* Rsheet_INFO */
create view SWCOMPANY.Rsheet_INFO (Sheet_id, Prod_name, Step_no, Step_name)
as select SWCOMPANY.ROUTING_SHEET.Sheet_id, SWCOMPANY.PRODUCT.Name, SWCOMPANY.RSHEET_STEP.Step_no, SWCOMPANY.RSHEET_STEP.Step_name
from SWCOMPANY.RSHEET_STEP, SWCOMPANY.ROUTING_SHEET, SWCOMPANY.PRODUCT
where SWCOMPANY.ROUTING_SHEET.Product_id = SWCOMPANY.PRODUCT.Product_id and SWCOMPANY.RSHEET_STEP.Sheet_id = SWCOMPANY.ROUTING_SHEET.Sheet_id;
      
/* BOM_INFO */
create view SWCOMPANY.BOM_INFO (Bom_id, Prod_name, Part_name, Part_quantity)
as select SWCOMPANY.BOM.Bom_id, SWCOMPANY.PRODUCT.Name, SWCOMPANY.PART.Name, SWCOMPANY.BOM_W_PART.Quantity
from SWCOMPANY.BOM, SWCOMPANY.PRODUCT, SWCOMPANY.PART, SWCOMPANY.BOM_W_PART
where SWCOMPANY.BOM_W_PART.Bom_id = SWCOMPANY.BOM.Bom_id and SWCOMPANY.BOM_W_PART.Part_id = SWCOMPANY.PART.Part_id and SWCOMPANY.BOM.Product_id = SWCOMPANY.PRODUCT.Product_id;
